FROM mcr.microsoft.com/devcontainers/cpp:1-debian-11

# Install npm and nodejs for the frontend

RUN apt-get update && apt-get -y install --no-install-recommends npm nodejs

# Install binaryen for wasm

RUN apt-get update && apt-get -y install --no-install-recommends binaryen


